enum NetErrCode {
	NET_TIMEOUT = -7,
	NET_CONNECT_FAIL = -6,
	NET_SYSTEM_ERROR = -5,
	NET_RECV_ERROR = -4,
	NET_SEND_ERROR = -3,
	NET_SEND_OVERFLOW = -2,
	NET_PACKET_ERROR = -1,
	NET_SUCCESS = 0
};
